### ISSUE TITLE
Does not build with latest `lsp-types` (0.94.1)

### ISSUE THREAD

**Issue by smoelius** [regexident/cargo-modules#196]
`cargo-modules` does not build with the latest version of `lsp-types` (0.94.1), which was released just a few hours ago.
```
$ cargo update -p lsp-types
    Updating crates.io index
    Updating lsp-types v0.94.0 -> v0.94.1
$ cargo check
    Checking ra_ap_rust-analyzer v0.0.163
error[E0063]: missing field `diagnostic_provider` in initializer of `ServerCapabilities`
  --> .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_rust-analyzer-0.0.163/src/caps.rs:25:5
   |
25 |     ServerCapabilities {
   |     ^^^^^^^^^^^^^^^^^^ missing `diagnostic_provider`
```

As a consequence of the above `cargo install cargo-modules` also fails. `cargo install cargo-modules --locked` is a workaround.

**Comment by adsick** [comment]
Already spent  too much time trying to compile it... First time it was a workspace with a specified rust toolchain version and for some reason cargo respected that (the error was use of unstable method). Now this. Thanks for the workaround.

**Comment by massmr** [comment]
Thanks for the workaround

**Comment by regexident** [comment]
Thanks for the report! Could you check if the issue still exists for the just released 0.9.3 release?

**Comment by smoelius** [comment]
Sorry, just noticed this. It builds now.
