### ISSUE TITLE
Failed to compile with Rust 1.25

### ISSUE THREAD

**Issue by omarabid** [regexident/cargo-modules#16]
Rust Version: 1.25
Cargo Version:  0.26

```
error[E0433]: failed to resolve. Could not find `VisibilityKind` in `ast`
  --> src/builder.rs:86:59
   |
86 |                 let visibility = if item.vis.node == ast::VisibilityKind::Public {
   |                                                           ^^^^^^^^^^^^^^ Could not find `VisibilityKind` in `ast`

error[E0554]: #![feature] may not be used on the stable release channel
 --> src/main.rs:1:1
  |
1 | #![feature(rustc_private)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: failed to compile `cargo-modules v0.3.6`, intermediate artifacts can be found at `/var/folders/gl/j2cw1zks3ws2qkwqfl_bjwyw0000gp/T/cargo-install.kgfHsMtbq1IV`
```

**Comment by regexident** [comment]
Thanks!

I was aware of this for quite a while, yet couldn't find any time to fix it myself. 😕

Fortunately @hmvp fixed these things in [this PR](https://github.com/regexident/cargo-modules/pull/15#issuecomment-388024275), which we will be able to merge soon,
hopefully (once the remaining issues have been resolved). 💪🏻

**Comment by regexident** [comment]
The PR hasn't been merged yet, so I'm keeping this open for now. :wink:
Thanks again for filing!

**Comment by regexident** [comment]
Solved with 0.4.0
