### ISSUE TITLE
Crate does not compile with latest rust suite 1.55

### ISSUE THREAD

**Issue by fhaefemeier** [regexident/cargo-modules#92]
I tried to install `cargo-modules`with latest rust version 1.55 (rustc 1.55.0 (c8dfcfe04 2021-09-06) using latest docker image rust:1.55 and nativ on MacOSX). The command `cargo install cargo-modules` print the error message
```
   Compiling ra_ap_ide_db v0.0.72
error[E0432]: unresolved import `base_db::salsa::SweepStrategy`
 --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.72/src/apply_change.rs:6:35
  |
6 |     salsa::{Database, Durability, SweepStrategy},
  |                                   ^^^^^^^^^^^^^ no `SweepStrategy` in `salsa`

error[E0599]: no method named `sweep` found for struct `QueryTable` in the current scope
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.72/src/apply_change.rs:50:41
   |
50 |         base_db::ParseQuery.in_db(self).sweep(sweep);
   |                                         ^^^^^ method not found in `QueryTable<'_, ParseQuery>`
```
and many more (see attached file). It ends with
```
error: failed to compile `cargo-modules v0.5.4`, intermediate artifacts can be found at `/tmp/cargo-installSx2FpJ`

Caused by:
  build failed
```
[modules.log](https://github.com/regexident/cargo-modules/files/7312990/modules.log)
